language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk11
  - openjdk8

matrix:
  fast_finish: true

before_install:
  - pip install --user -r requirements.txt

script:
  - mvn install -DskipSphinxTests=true

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -DskipTests=true deploy"
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
