---
language: java
cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    packages:
      - python3-pip

jdk:
  - openjdk11
  - openjdk8

matrix:
  fast_finish: true

before_install:
  - pip3 install --user -r requirements.txt

script:
  - mvn install -DskipSphinxTests=true

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -DskipTests=true deploy"
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
